twilio/flex-plugin-library-conference

.github/workflows/build.yaml

JIRA: [FLEXY-4290](https://issues.corp.twilio.com/browse/FLEXY-4290)
Adding codecov github action to generate code coverage reports

Added codecov action

---

package.json

package.json updates

---

codecov.yaml
ui-src/src/ConferencePlugin.tsx

Check code cov status check

---

codecov.yml
ui-src/src/ConferencePlugin.tsx

Code cov status check after removing codecov yaml

---

.github/workflows/bundle.yaml
ui-src/src/ConferencePlugin.tsx

Use github app token in github actions

Updated workflow to approve and merge PR to upload bundle as assets

---

.github/workflows/bundle.yaml
ui-src/src/ConferencePlugin.tsx

Updated master to main in workflow

Updated master branch to main in workflow for creating bundle

---

.github/workflows/test.yaml
sonar-project.properties

Removing twilio and plugin cli from test workflow 

Removing twilio and plugin cli from test workflow

---

DETAILS.md

Details updates

---

.github/workflows/test.yaml
sonar-project.properties

JIRA: [FLEXY-4296](https://issues.corp.twilio.com/browse/FLEXY-4296)
- Updated to send code coverage and analysis information to sonar cloud via github action

Added sonar cloud code scan

---

sonar-project.properties

JIRA: [FLEXY-4296](https://issues.corp.twilio.com/browse/FLEXY-4296)
Sonar test coverage report showing less coverage. 
Modifying and checking sonar properties to see if it updates the coverage information.

Added src files path

---

CHANGELOG.md

FLEXY-4332-b added changelog

---

ui-src/src/flex-hooks/actions/HangupCall.ts

updated log message

---

README.md
codecov.yml
test-utils/renderer.tsx
ui-src/src/components/ConferenceDialog/ConferenceDialog.tsx
ui-src/src/components/ConferenceDialog/__tests__/ConferenceDialog.test.tsx
ui-src/src/components/ConferenceDialog/__tests__/__snapshots__/ConferenceDialog.test.tsx.snap
ui-src/src/components/ConferenceMonitor/ConferenceMonitor.tsx

help link updates

---

.github/workflows/tag.yaml
ui-src/src/components/ConferenceDialog/ConferenceDialog.tsx
ui-src/src/utils/Analytics.ts
ui-src/src/utils/__tests__/Analytics.test.ts

JIRA: [FLEXY-4563](https://issues.corp.twilio.com/browse/FLEXY-4563)
Integrated Segment analytics and added track events
On adding conference participant, Segment track call should be made

FLEXY-4563 Integrated Segment analytics and added track events

---

sonar-project.properties

JIRA: [FLEXY-4614](https://issues.corp.twilio.com/browse/FLEXY-4614)

Flexy 4614 b sync jest and sonar props

---

sonar-project.properties

JIRA: [FLEXY-4614](https://issues.corp.twilio.com/browse/FLEXY-4614)

FLEXY-4614 adding sonar exclusions

---

functions/setup.js

JIRA: [FLEXY-4799](https://issues.corp.twilio.com/browse/FLEXY-4799)

FLEXY 4799 updated serverless builds to use latest node runtime

---

functions/twilio-wrappers/conference-participant.private.js
functions/twilio-wrappers/programmable-voice.private.js

JIRA: [FLEXY-4799](https://issues.corp.twilio.com/browse/FLEXY-4799)

FLEXY 4799 added utils package

---

package-lock.json
package.json
ui-src/package-lock.json
ui-src/package.json

JIRA: [FLEXY-4799](https://issues.corp.twilio.com/browse/FLEXY-4799)

FLEXY-4799 updated telemetry package version

---

package-lock.json
package.json
ui-src/package-lock.json
ui-src/package.json
ui-src/src/components/ConferenceDialog/ConferenceDialog.tsx
ui-src/src/components/ConferenceDialog/__tests__/ConferenceDialog.test.tsx
ui-src/src/components/ParticipantActionsButtons/ParticipantActionsButtons.tsx
ui-src/src/components/ParticipantActionsButtons/__tests__/ParticipantActionsButtons.test.tsx
ui-src/src/flex-hooks/states/ConferenceSlice.ts

JIRA: [FLEXY-4799](https://issues.corp.twilio.com/browse/FLEXY-4799)

FLEXY-4799 added fix for invalid numbers
